### ISSUE TITLE
[BUG] Wrong version string in webinterface

### ISSUE THREAD

**Issue by q-wertz** [lldap/lldap#1033]
**Describe the bug**
In the webinterface footer the version string is still 0.5.0
![image](https://github.com/user-attachments/assets/7d65ffa7-f103-4a1e-ac35-1850417b863d)
while version 0.6.0 is installed
```shell
root@machine:/home/user# lldap -V
lldap 0.6.0
```

**To Reproduce**
1. See footer of webinterface
2. In server console run `lldap -V`

**Expected behavior**
Version strings match.

**Logs**
If applicable, add logs to explain the problem.
LLDAP should be started in verbose mode (`LLDAP_VERBOSE=true` env variable, or `verbose = true` in the config). Include the logs in triple-backtick "```"
If integrating with another service, please add its configuration (paste it or screenshot it) as well as any useful logs or screenshots (showing the error, for instance).

**Additional context**
Installed from inofficial [package repo](https://download.opensuse.org/repositories/home:/Masgalor:/LLDAP/xUbuntu_24.04/)

**Comment by nitnelave** [comment]
Can you try clearing your cache? I think the wasm didn't get refreshed after the update.
