### ISSUE TITLE
[FEATURE REQUEST] LDAP Toolbox like Tools

### ISSUE THREAD

**Issue by Technikte** [lldap/lldap#1067]
**Motivation**
Some stuff would be very usefull/nice for selft hosted/home setups like https://self-service-password.readthedocs.io/en/stable/ .

**Describe the solution you'd like**
A way to let user reset their password and change "more" things on their own if needed.

**Describe alternatives you've considered**
Alternative would something like this https://github.com/tiredofit/docker-self-service-password or some other ldap toolbox. But would be nice to get something build in to elimate the need for other tool.

**Additional context**
I think it would fit perfect since lldap is more oriatend to self hosting in homelab and so.

**Comment by nitnelave** [comment]
There's already a built-in password reset flow through email. You can enable it by filling in the SMTP settings and allowing password resets (see the config template at the root of the repo). Please have a look and tell me whether that fits the bill :)

**Comment by Technikte** [comment]
Oh really, I didnt see any option like this yet, but I fired only a quick "demo" up local without stmp.
I will report back and mabye close this issue when it fits my needs.
Thanks in advance.

**Comment by Technikte** [comment]
I have enabled it and it seems to work. Maybe only some kind of basic anti bot captcha would be nice or something along these lines and "support basic complexity requirements" like the pr https://github.com/lldap/lldap/pull/1024 would be generall nice to have.
