### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by nitnelave** [lldap/lldap#20]
Provide functionality to translate strings, and actual translations.

- [ ] Provide the infrastructure
- [ ] Move all strings to templates
- [ ] Create translations for main languages
  - [ ] French
  - [ ] Spanish
  - [ ] German
  - [ ] Chinese
  - [ ] More if contributed.

**Comment by olaxe** [comment]
I can take care of the French language

**Comment by marinkaberg** [comment]
Russian is here

**Comment by nitnelave** [comment]
Thanks for volunteering, but we're not ready to accept translations yet, the infrastructure is not there :)

**Comment by nitnelave** [comment]
Actually, I think we're not going to do this: it would be a drag on new features and overall maintenance, for little gain: most end users will only see the login page, and I assume most everyone can navigate that in English. I know we're letting some people down, but I think that google translate/Firefox translations can fill the gaps. The effort is not worth it here.
