### ISSUE TITLE
pam support?

### ISSUE THREAD

**Issue by malbarbo** [lldap/lldap#294]
I'm interested in using lldap to authenticate linux users using pam, but it seams that lldap does not support pam, is this the case? If so, would someone provide some guidance to me so I can work on this?

**Comment by nitnelave** [comment]
I'll keep this issue open since we might want to have a nicer interface for it, such as finding a user ID that isn't taken yet and so on, but #67 comes first.

**Comment by nitnelave** [comment]
You can now create custom attributes with https://github.com/Zepmann/lldap-cli

Can you give it a try?

The plugin system will come way later with #714

**Comment by nitnelave** [comment]
Pam is now supported.
