### ISSUE TITLE
Ability to remove profile picture

### ISSUE THREAD

**Issue by wailashi** [lldap/lldap#358]
Currently there is no way to remove the profile picture of a user after it has been set.
The user page could have a button to remove the photo if one is set.

Thanks for a great tool!

**Comment by pixelrazor** [comment]
Some notes from me tinkering with it so far: it's been a pain to get lldap to store NULL - the closest i can  get is an empty blob (which is effectively the same) - the only issue is ensuring some sort of consistency to make sure we're returning NULL in the graphql queries

**Comment by nitnelave** [comment]
For firstName/lastName, that's what I did in GraphQL: an empty string means no name. I'm not opposed to doing the same thing with the avatar.

**Comment by pixelrazor** [comment]
I would like for there to be some sort of consistency for representations - i don't care as much what it is under the hood (though consistency there is nice too) but at the very least for external interfaces. Treating avatar the same as the name fields would be perfect

**Comment by nitnelave** [comment]
Then you have my blessing if you want to do this change!
