### ISSUE TITLE
Allow setting the `key_file` value as an env var

### ISSUE THREAD

**Issue by onedr0p** [lldap/lldap#504]
This is a continuation of a discussion in https://github.com/nitnelave/lldap/issues/502

There's two point that could be covered here, ideally number 2 makes the most sense to me.

In order to simplify running lldap in high availability...

1. The user can run lldap and obtain the contents of the `key_file` which would allow them to set this via env, or
2. Remove the logic for generating a private key and allow the user to create and set the `key_file` value in the env or config file.

**Comment by miberecz** [comment]
I'm just facing the exact same issue as @onedr0p in the mentioned ticket. 
I'm trying to create a Kubernetes deployment without any persistent storage, so make it truly stateless by providing every configuration by environment variables or secrets, so it can be scaled to multiple replicas on demand. 
I just found out that the private_key needs to be created by the lldap server itself. 

I realize the scope of this project is to provide a very simple LDAP solution for mainly selfhosters, so make it as simple as possible, but I strongly support the second solution previously mentioned. 
If a JWT sercet can be a simple variable in the config,  private_key should be also.

**Comment by nitnelave** [comment]
As I explained in the linked discussion, the contents of the key file _have_ to be generated by LLDAP, they're not just random bytes like the JWT key. So anyway you'll have to run LLDAP at least once to generate the key (which you could conceivably then pass by environment variable).

Actually, now that I think about it, I wonder if there is a way to use a seeded RNG to re-generate the key file every time? That would allow an easy external secret generation, with a consistent (as long as we use the same code) generated key.

**Comment by miberecz** [comment]
Okay, I get it. 
In this case one could implement an [initContainer](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) which runs before the Lldap server starts. Creates the private_key which can be mounted in the actual container running the server. 
Only if there would be a command like `lldap create-key`

About the seeded RNG you mention. I'm not sure about the math behind the crypto stuff, but if there would be a fixed value, and with that value always the same key is generated, then we could just use that as a config parameter, and the key still be created by the server.

**Comment by onedr0p** [comment]
I've thought about the create key command and using an `initContainer` but it's still not great. That command would need to be idempotent to not regenerate the key.

I'd rather effort be put into making it so lldap can be 100% env driven.

**Comment by nitnelave** [comment]
See https://github.com/lldap/lldap/pull/549, you can now set a `key_seed` (or `LLDAP_SERVER_KEY_SEED`) to generate the private key from a stable seed. Note that the private key generated is _not_ going to be the same as the existing `server_key` file that you had previously, so all the passwords will have to be reset.

**Comment by miberecz** [comment]
I have tested it, and works like a charm so far. 
Only minor problem I noticed, that the value of the `key_seed  ` is not censored in the logs at startup.

**Comment by onedr0p** [comment]
I have deploy this in my kubernetes cluster with the following config (I use Flux):

https://github.com/onedr0p/home-ops/tree/main/kubernetes/apps/default/lldap/app

My only question would be is the data directory needed? I have it set to emptyDir now.

**Comment by onedr0p** [comment]
Any reason you need to include that file? It looks like everything is able to be set via env.

**Comment by nitnelave** [comment]
@miberecz I'm making the key_seed a secret here: https://github.com/lldap/lldap/pull/554
We'll still know _whether_ there is a `key_seed`, but not what it contains.
