### ISSUE TITLE
Support ECKey as private key for lldaps

### ISSUE THREAD

**Issue by Michsior14** [lldap/lldap#525]
Caddy defaults to [ed25519 tls key type](https://caddyserver.com/docs/caddyfile/options#key-type). 
It would be cool if the certificates generated with standard configuration of Caddy would work with lldap as well.

**Comment by nitnelave** [comment]
Side note: it would be amazing if you could contribute your Caddy config as well ;)

**Comment by Michsior14** [comment]
Caddy config is very simple: 

```
lldap.example.com {
    log
    
    # lldap frontend is listening on 8080
    reverse_proxy http://127.0.0.1:8080
    
    tls {
        # dns acme challange using aws route 53
        dns route53
    }
}
```

Workaround that I use for now is to force RSA certificate via global options:
 
```
{
    key_type rsa4096
}
```

The only thing that is not the greatest is that the lldap needs to be restarted every night to ensure the latest certificate from caddy (there is no signal) is used.

**Comment by nitnelave** [comment]
Why do you need to change the certificate every night? Usually you can get much longer-lived certificates, at least 3 months, no?

**Comment by Michsior14** [comment]
I am using incron to detect the changes and restart only when needed, but without it you won't know when the change happens (caddy can do that week before the 3 months span or it can be days/hours) so the safest bet I guess.
