### ISSUE TITLE
Footer in Dark Mode is not readable

### ISSUE THREAD

**Issue by SnowJuli** [lldap/lldap#538]
The Footer of the LLDAP Page isn't very readable because the font and the footer have the same color.
![image](https://user-images.githubusercontent.com/49914615/230742152-69cc076e-6d05-4c66-af6c-cea42db94963.png)

A closer look into the DevTools of Firefox show that the font-color option is out greyed:
![image](https://user-images.githubusercontent.com/49914615/230742196-9b6a629a-1376-4129-8d60-06b633209b6d.png)

Info:
- Latest Version of the `stable` Docker Image
- Firefox 111.0.1
- Librewolf 107.0.1
- Edge 112.0.1722.34

**Comment by martadinata666** [comment]
Can you try this, [personal lldap demo test](https://lldap-dedyms.p.projectsegfau.lt) can you try clearing browser cache and cookies, or you are using some external `theming` extensions?

**Comment by SnowJuli** [comment]
Yup, just tested it again and force deleting cache resolved the issue. Will close the issue now.
