### ISSUE TITLE
ghcr.io package not public?

### ISSUE THREAD

**Issue by MrOnak** [lldap/lldap#547]
I was happy to see you're offering another registry to pull the image from but it seems that the package on ghcr.io isn't public? 

```
% docker pull ghcr.io/lldap/lldap
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/lldap/lldap/manifests/latest": unauthorized
```

**Comment by nitnelave** [comment]
Good catch! It should be public now.
