### ISSUE TITLE
ambiguous column name: display_name

### ISSUE THREAD

**Issue by jim-kirisame** [lldap/lldap#562]
LLDAP return result code 80 when query with cn

```
(&(cn=*test*))
```

Error message: 
```
Error while searching user "ou=people,dc=******,dc=***": Database error: `Query Error: error returned from database: (code: 1) ambiguous column name: display_name`.
```

**Comment by nitnelave** [comment]
Thanks, I'll look into that. We use an ORM, but it does lead to some naming conflicts, that's a bit unfortunate.

**Comment by nitnelave** [comment]
Note that I'm in the middle of an SQL refactoring while working on #67, so maybe it'll fix that. I still need to add the test case, though.
