### ISSUE TITLE
Deleted admin account gets recreated with default password

### ISSUE THREAD

**Issue by hpaantee** [lldap/lldap#563]
First of all, thanks for developing this great software. It's easy to use and deploy.
However, I just noticed that when you delete the default admin "admin", it gets recreated with the default password and privileges. 
That means, to e.g. protect against brute force attacks, deleting it and using another admin account (with different name) instead, this recreates the default one.
This seems dangerous, as people might not suspect that behavior and allows access to ldap via the typical admin/password combo. 

Currently I changed it's password and removed it from the administrator group. But lldap should just check if there is at least one other user member of the administrator group.

**Comment by nitnelave** [comment]
I think we can simply check whether there are any users, it shouldn't be possible as an admin to remove yourself from the admin group, so there will always be one.
