### ISSUE TITLE
Unsupported operation: DelRequest

### ISSUE THREAD

**Issue by fengerzh** [lldap/lldap#569]
When use `ldapdelete` command to delete an entry, an error showed as below:

```
# ldapdelete "uid=aaaa,ou=people,dc=some,dc=com" -H ldap://ldap.server.com:3890 -D "uid=admin,ou=people,dc=some,dc=com" -w "adminpassword"
deleting entry "uid=aaaa,ou=people,dc=some,dc=com"
ldap_delete: Server is unwilling to perform (53)
	additional info: Unsupported operation: DelRequest(
    "uid=aaaa,ou=people,dc=some,dc=com",
)
```

**Comment by nitnelave** [comment]
That is indeed an unsupported operation. What's your use case? The recommended way to modify users on the server is either the web frontend or the GraphQL API.

**Comment by fengerzh** [comment]
> 

I'd like to synchronize members with another database, when some user quit, programatically delete the user from ldap.

**Comment by nitnelave** [comment]
In that case, the recommended way is to use the GraphQL API

**Comment by nitnelave** [comment]
Closing in favor of #518
