### ISSUE TITLE
Ability to lock / hide fields

### ISSUE THREAD

**Issue by fgardt** [lldap/lldap#570]
# Idea

Allow administrators to mark certain fields as either locked (as in not editable) or hidden for normal users.
An extension to this could be to link the locking / hiding to groups so that certain groups can edit / see fields that might be relevant to them.

# Why

In certain scenarios it might be wanted / needed to lock users from editing certain fields of their own profile.
For example their email which might be assigned to them so it could potentially break things if changed.

Also once #67 allows for an arbitrary amount of fields not all of them might be relevant to / changeable by a user so hiding / locking them would be great.

**Comment by fgardt** [comment]
It would just be a nice-to-have that came to mind while writing the issue.
I certainly see that this will make it quite a bit more involved than just hiding/locking on its own which is why I mentioned it as a possible extension and not the main request.

**Comment by nitnelave** [comment]
Actually, after a closer look, it's already in the scope of #67, there's a IsUserVisible and IsUserEditable bit per field.
