### ISSUE TITLE
Please publish to crates.io

### ISSUE THREAD

**Issue by alexmyczko** [lldap/lldap#571]
I wanted to create a debian package of this, however in #debian-rust i was told:
that would simplify the packaging significantly

^ if it was on crates.io

**Comment by nitnelave** [comment]
The next version is breaking, so I don't want to release too early. I prepared what we need for a crate, but I'll publish it when I release the 5.0

**Comment by nitnelave** [comment]
Blocked by https://github.com/lldap/lldap/issues/579

**Comment by nitnelave** [comment]
See also https://github.com/lldap/lldap/pull/578
