### ISSUE TITLE
Customize (audit) logging for login events

### ISSUE THREAD

**Issue by Phype** [lldap/lldap#575]
Would it be possible to add support for logging login-events (from both LDAP and HTTP interfaces) for log-review, ie. as a centralized source of security events from multiple connected applications?
For HTTP this is pretty straight-forward and for LDAP, one could just log LDAP BIND operations, which are equivalent with someone attempting to log in at a connected application.

I could potentially create a PR which just logs these events to stdout, but i'm unsure whether this would integrate with https://github.com/lldap/lldap/issues/17 and it should probably be configurable too.

**Comment by nitnelave** [comment]
Hmm, assuming that the HTTP login events had the username (the LDAP ones already do), could you do with the existing log? I think with some grep it should be possible to extract the login events from the logs.

This is not a use case that is high in my priority list, I'm not sure I want to complexify the software to support it.

**Comment by nitnelave** [comment]
I'm going to close this as out-of-scope but implementable as a plugin once we have #714 (in the distant future).

**Comment by nitnelave** [comment]
#714 should indeed provide what you need. It's being actively worked on, there should be significant development in the next few weeks.
