### ISSUE TITLE
Naming of migration-tool

### ISSUE THREAD

**Issue by bendlas** [lldap/lldap#581]
The naming of `migration-tool` seems too generic for installing to the system PATH.

Can we rename it to `lldap_migration_tool`? This would also make it consistent with `lldap_set_password`.

**Comment by nitnelave** [comment]
Interesting timing, I just did precisely that... Yesterday :)

**Comment by martadinata666** [comment]
https://github.com/lldap/lldap/pull/577

**Comment by bendlas** [comment]
neat :)
