### ISSUE TITLE
Problems setting up Nextcloud with Authelia OIDC and LLDAP

### ISSUE THREAD

**Issue by tenekev** [lldap/lldap#587]
Hello,
I followed the [Nextcloud ](https://github.com/lldap/lldap/blob/main/example_configs/nextcloud.md)and [Nextcloud OIDC](https://github.com/lldap/lldap/blob/main/example_configs/nextcloud_oidc_authelia.md) tutorials in the hopes to have a universal SSO experience.

They work fine independently - LLDAP users are populated into Nexcloud AND you can login with Authelia OIDC. 

**The problem** is that when you try to login with OIDC (SocialLogin app) does not use the pre-existing users from LLDAP and instead creates a new user with the same info. This behavior is breaking if I enable **"Prevent creating аn account if the email address exists in another account"** and results in failed login. with a message **"Email already registered"**

How do I force OIDC to login into an existing user instead of attempting to create new ones?

**Comment by nitnelave** [comment]
Hmm, I think that's a question better asked to the nextcloud community. It seems you have lldap configured correctly, but I don't know how to configure nextcloud for oidc with an LDAP backend as source for accounts.

But if you do find out, feel free to contribute this back to the lldap nextcloud config for the next person!

**Comment by tenekev** [comment]
I figured it out. It was working fine. I just didn't know that you need to add the OIDC provider from every profile manually before attempting to login with it. I think it should be mentioned in the [nextcloud oidc config](https://github.com/lldap/lldap/blob/main/example_configs/nextcloud_oidc_authelia.md).

[User] > Settings > Social Login > Add OIDC
or 
https://nextcloud.example.tld/settings/user/sociallogin

**Comment by nitnelave** [comment]
@tenekev do you think you could update the nextcloud config to mention instructions to configure OIDC?

**Comment by tenekev** [comment]
Yes. I have documented it partially and this gives me an incentive to finish it.
