### ISSUE TITLE
[Feature Request] Log to log file instead of console.

### ISSUE THREAD

**Issue by Realmlist** [lldap/lldap#588]
**Request:**
Add the possibility to log to a log file instead of the console.
This is especially handy for docker, since the log file can be bound to storage outside of the docker.img, thus making it not clog up.

**Reason for request:** 
The LLDAP log file was 25MB after running for 3 days, and I could only access it by using `docker inspect` and export it through `docker logs`.

**Comment by nitnelave** [comment]
You can achieve that directly in docker compose: https://docs.docker.com/compose/compose-file/compose-file-v3/#logging

**Comment by Realmlist** [comment]
My apologies, I was not clear in my request, I think.

I would like to have the ability to choose where the logs are stored. 
Like many docker containers they're usually stored in the folder that gets linked to your host's permanent storage volume.

<details><summary>For example</summary>
<img width="194" alt="image" src="https://github.com/lldap/lldap/assets/2737082/8cbdafab-db24-42b3-b822-eaee35513ae4">
<img width="216" alt="image" src="https://github.com/lldap/lldap/assets/2737082/c1d43cd9-73d4-4b32-8d4a-0593c9c7ab47">
<img width="203" alt="image" src="https://github.com/lldap/lldap/assets/2737082/204e1516-9fbb-4673-beb8-f1bee10513c5">

</details>

It's mostly a QoL request, as the logs can be extracted with `docker logs`, but it's just more handy to be able to see your log files through a network share. 🙂

**Comment by nitnelave** [comment]
Oh, right. This should also be doable in docker-compose:
`command: bash -c "/app/docker-entrypoint.sh run --config-file /data/lldap_config.toml > /path/to/log/command.log 2>&1"`
