### ISSUE TITLE
Use separate configuration options for database credentials

### ISSUE THREAD

**Issue by 0hSnap** [lldap/lldap#590]
Currently, LLDAP requires the entire database url, including the username and password, to be provided in the LLDAP_DATABASE_URL configuration option. However, this poses an inconvenience when using docker secrets, as a new docker secret needs to be created specifically for the database url. To enhance security and convenience, I suggest adding two additional configuration options, LLDAP_DATABASE_USER and LLDAP_DATABASE_PASS, which would allow for the separation of the database credentials from the database url. With this change, it would be possible to use the same docker secrets used to set the username and password for the database user in the DBMS container within LLDAP.

**Comment by nitnelave** [comment]
Handling the password separately from the URL is a big hassle compared to
what we do now. We'd have to have configuration options for database type,
host, port, username and password, and validate them (including the lack of
username password for SQLite), then reformat them into the existing
variable. All the while we have to keep supporting the URL to avoid
breaking people's config. That's a bit of a tall ask to deduplicate a
secret.

If you really want something like that, then I suggest you change the
startup script in the docker to load your secret and add it to the
environment variable for the database URL dynamically.
