### ISSUE TITLE
Format for changing password from inside container.

### ISSUE THREAD

**Issue by tetricky** [lldap/lldap#597]
```
./lldap_set_password --base-url http://localhost:17170/ --admin-username admin --admin-password <admin password> --username user --password <user password>
```
Fails with error

```
Error: While logging in

Caused by:
    expected value at line 1 column 1
```

Whereas
```
./lldap_set_password --base-url http://localhost:17170 --admin-username admin --admin-password <admin password> --username user --password <user password>
```
Completes successfully.

**Comment by nitnelave** [comment]
Note that if we have a double-slash, it should be fixed on the client side. Probably by actually parsing the URL (also provides validation), maybe setting a default of localhost:17170 on the way.

**Comment by eztEgyed** [comment]
I have got:
Error: HTTP status client error (400 Bad Request) for url (http://localhost:17170/auth/opaque/register/start)

What does it mean?

**Comment by nitnelave** [comment]
@eztEgyed how did you get that? From running lldap_set_password?
