### ISSUE TITLE
Emails do not have a message_id

### ISSUE THREAD

**Issue by Masgalor** [lldap/lldap#608]
I noticed that password-reset-mails sent from my system have a higher spam score as expected.
This is because the mails are missing the `message-id header`.

Usually it is up to the originating client to add this header.
But many email-providers add it automatically if it is missing, because those mails would very likely get flagged as spam and lower their trust score.

Anyway it would be a good thing to not rely on the mailserver to "repair" the mails for us.

I can not implement it myself but here is how another project which is also using `lettre` solved it.
Maybe someone can get a PR going.
https://github.com/dani-garcia/vaultwarden/blob/1.28.1/src/mail.rs#L594-L599

References:
https://en.wikipedia.org/wiki/Message-ID
https://docs.rs/lettre/latest/lettre/message/header/struct.MessageId.html

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this.

**Comment by nitnelave** [comment]
Sounds good! Tell me if you need help. And don't hesitate to join the discord server where you can ask a quick question.
