### ISSUE TITLE
Improved Image Versioning and Release Cycle

### ISSUE THREAD

**Issue by RedlineTriad** [lldap/lldap#613]
https://hub.docker.com/r/nitnelave/lldap/tags

Currently only the latest images seem to be frequently updated, but it would be nice to have daily, or per PR images.
I use renovate bot to automatically update images, but when using latest that doesn't work.
But if I were to use the named images I would be months behind in the development cycle, which would be annoying.

Grafana images have very nice versioning as an example:
https://hub.docker.com/r/grafana/grafana/tags

Also, hello from hackernews :D

**Comment by martadinata666** [comment]
My 2 cents here, why do we need daily images? or even per PR image cluttering up the tags page. Can it use `:main` tag? If it can, then imo should take the issue to renovate as grafana `:main` work the same as lldap `:latest`, I assume it can't as the [renovate docs](https://docs.renovatebot.com/docker/) only accepting semver? The only exception is `ubuntu:something` or `debian:something`, it's just weird renovate don't want to support it for other images.

Then lastly yes, lldap on a slow pace as it a community project that time is not our friend.

Thanks for the input anyway ☕

**Comment by RedlineTriad** [comment]
If I use the main tag I don't know which image is actually deployed, I don't care much about semver but I do care about determinism and having software versions in git with rollback possibilities.

Or even with a bug report I can't say I just use latest, and using a months old version when reporting bugs is also bad. So the best thing I can do is go on the server manually and get the digest of the image, and even with that there might be no way to map it back to a git commit.

I would just like versioned builds that are as up to date as possible, what those versions are is not that important.
