### ISSUE TITLE
WEBhook configuration

### ISSUE THREAD

**Issue by eztEgyed** [lldap/lldap#621]
It would be nice if you could define an after change webhook.
After any data change, the webhook would call the url with POST method, sending the what-to-change as data.

**Comment by nitnelave** [comment]
I'm not opposed to the idea, but I'm not sure I'll have time for it. If you want to contribute, we can start with a design doc to align on the details, and then PRs.

**Comment by nitnelave** [comment]
I'll close this as out-of-scope, implementable as a plugin once we have #714  (in the distant future)
