### ISSUE TITLE
Sort groups list on user view

### ISSUE THREAD

**Issue by mechanarchy** [lldap/lldap#623]
On the user view, the list of groups that the user is in has no defined sort, nor is the ordering stable. The group list changes order with each refresh. Please can this list be alphabetically sorted so that it is stable between refreshes and matches the ordering of groups on the group view page.

I'm not familiar with Rust enough to implement this myself but I believe the code that needs to be changed is here:
https://github.com/lldap/lldap/blob/7d1f5abc137821c500de99c94f7579761fc949d8/app/src/components/user_details.rs#L149

Or it may need to be implemented upstream in the GraphQL API.

**Comment by nitnelave** [comment]
Sorted the groups upstream so that graphql always returns a sorted list.
