### ISSUE TITLE
Fallback note for useres with incompatible browsers

### ISSUE THREAD

**Issue by Masgalor** [lldap/lldap#636]
### Discussed in https://github.com/lldap/lldap/discussions/635

If the browser is not able to handle the frontend there is no fallback/warning/error, so the user will just see an empty page.
For my limited understanding this happens if JavaScript is completely disabled, or if JavaScript is enabled but JIT is disabled.
There may be more relevant factors but those are the ones I noticed.

It would be great to have some kind of fallback to inform the user about their incompatible browser.
Even if the user can't make any sense of the displayed message they can seek help more easy.

**Comment by nitnelave** [comment]
Can you check that you get the correct warning with the new build?

**Comment by Masgalor** [comment]
I can confirm that I get the correct warnings shown.

Could we bring this change to `index_local.html` as well?

**Comment by nitnelave** [comment]
Merged in `index_local.html` as well!
