### ISSUE TITLE
uidNumber attribute missing

### ISSUE THREAD

**Issue by jacobw** [lldap/lldap#640]
The uidNumber POSIX attribute is missing. This causes LibreNMS to fail in unexpected ways.

Tested on lldap version 0.4.3 and LibreNMS version 23.5.0

LibreNMS issue here: https://github.com/librenms/librenms/issues/15197
I suspect this may just be an lldap issue though.

**Comment by jacobw** [comment]
There is a config option in LibreNMS to change uidNumber to uid which fixed this issue.

**Comment by nitnelave** [comment]
@jacobw could you maybe submit a PR with an example config for librenms?

**Comment by jacobw** [comment]
Yes I will.
