### ISSUE TITLE
Compilation ran my VM out of memory

### ISSUE THREAD

**Issue by wjk** [lldap/lldap#660]
I set to compile lldap from source, following the instructions in the README. It compiled all the dependent modules, but hung when it got to the lldap binary itself. I noticed that at one point during the build, the system UI was not responsive to my inputs. I left it to sit for a while and came back to see that the compiler process was killed (as in an actual SIGKILL). Given the symptoms, it is likely that the kernel’s OOM killer did this. Does anyone have any hints as to what might be going wrong?

Environment:
* M1 MacBook Air (arm64 processor)
* Virtualization program: [UTM](https://getutm.app/) version 4.3.5
* OS: Debian 11 “Bullseye”
* Reported memory: 3.8GB
* Rust compiler version: 1.72.0

**Comment by Masgalor** [comment]
If you want to build LLDAP for Debian_11 your vm will need at least 4GB of memory and 10GB of disk space (without swap).
[Source](https://build.opensuse.org/package/statistics/home:Masgalor:LLDAP/lldap/Debian_11/x86_64)
