### ISSUE TITLE
[keycloak] - Read-only

### ISSUE THREAD

**Issue by aparrot89** [lldap/lldap#665]
Why is lldap with keycloak necessarily in read-only mode?
Isn't it possible to also have the "write" right in keycloak?
https://github.com/lldap/lldap/blob/main/example_configs/keycloak.md

**Comment by Ziomal12** [comment]
Last time I checked lldap didn't support write through ldap protocol. While you can set it in Keycloak to write, it's pointless as users it creates are messy. @nitnelave is considering implementing it, but it massively increases workload on the project.

**Comment by aparrot89** [comment]
Thanks for the answer. :-)
Why is it possible to write from authelia?
Aren't the same technologies used?

**Comment by nitnelave** [comment]
It's possible to create basic users via LDAP, but the capacity is very limited: you can't edit them after creation, you can't add them to a group. You really can't do much.

**Comment by aparrot89** [comment]
Thanks a lot for the answer
