### ISSUE TITLE
just webui for openldap

### ISSUE THREAD

**Issue by cyberb** [lldap/lldap#673]
Is it possible to use just webui part with existing openldap server?

I have an existing ldap sever and I am not ready to migrate it to lldap backed (if it is even possible) just yet: https://github.com/syncloud/platform

**Comment by nitnelave** [comment]
Nope. The web ui is built on top of the graphql API, which is LLDAP specific.

**Comment by nitnelave** [comment]
Note that we have migration tools to go from openLdap to LLDAP.

That doesn't port the passwords though, and the capabilities are pretty limited.
