### ISSUE TITLE
[Feature Request] sudoers support

### ISSUE THREAD

**Issue by SingingFrog7** [lldap/lldap#702]
Hey guys,

   Is there any plan to support sudoers in the future? 

I'd be migrating from my current LDAP server if it was supported as I use it to give sudo access to users on all my vms and containers

Thanks

**Comment by nitnelave** [comment]
Hi! I had a look at the sudoers LDAP configuration, and it seems that it won't be compatible with LLDAP's simple structure of just groups and users.

However, once #67 is implemented, we'll have support for PAM authentication so you can assign Unix groups with LDAP. If you configure your sudoers the old fashioned way (with visudo) based on groups, you can then assign permissions to people by adding them to LLDAP's groups.

**Comment by SingingFrog7** [comment]
Hello,  
   Sorry for my late reply and thanks for looking at it. It definitively could work for me, in fact I tried to switch from OpenLDAP to different other LDAP servers and I always came back to OpenLDAP because I use the sudoers (which I could change to having a sudoer group but I would have to add that group to all machines, which is doable) and I also use Samba, which I know is another complicated beast

I'll keep an eye on #67 and test it in my environment once it's implemented

Thanks for your time!
