### ISSUE TITLE
Password reset form should use HTTP POST

### ISSUE THREAD

**Issue by Azelphur** [lldap/lldap#704]
Minor issue, but password reset (and any other form) should ideally use HTTP POST. Currently the password reset form uses HTTP GET.

**Comment by PlayerSchark** [comment]
Just want to mention: I had caching issues with this

verbose log
```
HTTP request [ 148µs | 100.00% ] method: "GET" | uri: "/reset-password/step1"
┕━ 🐛 [debug]:  | status_code: 304
```

Browser:
```
Request Method:
GET
Status Code:
200 OK (from disk cache)
```
