### ISSUE TITLE
[BUG] lldap website auth's username is case sensitive, while password reset is not

### ISSUE THREAD

**Issue by evrardjp** [lldap/lldap#728]
**Describe the bug**
When logging in, I need to provide a username in a case sensitive manner (makes sense to me).
Yet, if I go to password reset page, I add a capital letter for the login to recover, and it will work.

If this is intentional, it can definitely confuse people "Why does the password reset work, but auth does not?"

**To Reproduce**
1. Create user in the web interface in lowercase letters
2. Go for self-service password reset page and enter the same username with an uppercase letter.
3. Receive password reset email
4. (Optional) try authenticate with uppercase user.

**Expected behavior**
Step 3 should not have worked without the correct case.

**Logs**
If you want logs I can provide some.

**Additional context**
Is that expected?

**Comment by lordratner** [comment]
When you create a user, it is not case sensitive. If you already have user "johndoe" you will not be able to create "JohnDoe"

I think everything should be case-insensitive (for usernames obviously) and force it to lowercase in the webui. Easier that way.
