### ISSUE TITLE
[BUG] Password reset UI is enabled even when the feature is disabled

### ISSUE THREAD

**Issue by nitnelave** [lldap/lldap#753]
It seems the probe is not working. 

With the precedent of https://github.com/lldap/lldap/pull/752, we can get rid of the probe and just inject the settings in the main.js.

**Comment by kosssi** [comment]
I have the same problem, when I set `LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET` to false the UI display « Forgot your password? » link. I would like reset password is only from my OIDC Authelia ;)

It's https://github.com/lldap/lldap/pull/449 feature ;)

**Comment by nitnelave** [comment]
It's just a frontend issue, meaning that even if users click on the button, they won't be able to reset their password. But yes, it's not ideal.
