### ISSUE TITLE
[FEATURE REQUEST] Documentation needs some clarification

### ISSUE THREAD

**Issue by senatormailman** [lldap/lldap#772]
**Motivation**
I am confused as how the underlying mechanisms handle configuration. I am using LDAP and I was reviewing the documentation about how to configure docker-mailserver that way. I wanted to use a secret to store this data but I notice in the helm chart's doc, there's not much detail about how to do that. I think based on what I am seeing in the `secret.yaml` template, if I just make my own secret and name it the helm chart (appended with `-secrets`) will cause that to work?

**Describe the solution you'd like**
I think for using secrets and configmaps, having a default and an expectation as to how to name those secrets/configmaps will help.

**Describe alternatives you've considered**
I have tried to just create a secret by hand. I have also tried to just leverage the pre-generated secret. Creating it by hand made me worried that I configured it wrong, the pre-generated secret basically confirmed that for me.

**Additional context**
I am running Rancher via K3s on x86_64 architecture. When I tried to make a secret, I created a key-value pair. That's why I feel that my secret was incorrect. I noticed that the pre-generated secret was just an RSA private key.

**Comment by nitnelave** [comment]
I think there's a bit of confusion here:
- you mention documentation about docker mail server, but I don't think we
have an example config for it in this repository. What's the documentation
in question? (Link?)
- you also mention a helm chart. Again, I don't think we have any in the
repository. Which one are you referring to?
- finally, regarding the secret: we have several secrets (well, mainly 2),
and they can be handled in different ways. Which secret are you referring
to?

All the documentation for the various configuration options (including
secrets) for LLDAP are in the sample config:
https://github.com/lldap/lldap/blob/main/lldap_config.docker_template.toml
In it, we describe the various values, how to configure them either in the
config file or with environment variables, and give some examples of how to
generate the secrets themselves. Moreover, when starting, LLDAP will emit a
warning if the secrets have their default values.

**Comment by senatormailman** [comment]
Woof, egg on my face. I have no idea how I did that!

This was for a different repo entirely!

My apologies!
