### ISSUE TITLE
[BUG] No documentation on SSL

### ISSUE THREAD

**Issue by r-vd-woude** [lldap/lldap#777]
This is not a bug, but I'm not sure were else to ask this question. 
If this is the wrong place, I'm sorry.

First of all: what an amazing pieces of software! It is very stable and easy to setup.

However, I would like to encrypt the traffic between LLDAP and the different services that connect to it, as they all share the same virtual Docker network (so I can add services to a reverse proxy).

But, there is not a lot of information available how to setup such encryption, and/or if it is really needed.

Sorry again if this is the wrong place, and thanks again for the software!

**Comment by nitnelave** [comment]
Hi! I think you're looking for LDAPS :)

Check the config template, there's an ldaps section. As for the services, it's usually as simple as changing the protocol to ldaps:// (and adjusting the port), but sometimes they have an extra flag to indicate whether LDAP traffic is encrypted. That should be included in the relevant configuration examples.

**Comment by r-vd-woude** [comment]
Awesome! Thanks for the quick response, will take a look!
