### ISSUE TITLE
[BUG] Repetitive Validation Loop for 'admin' User in lldap/lldap:2024-02-06-debian-rootless Container Logs

### ISSUE THREAD

**Issue by gcamblin** [lldap/lldap#837]
**Describe the bug**
A loop appears to be occurring in the container logs when validating accounts using the lldap/lldap:2024-02-06-debian-rootless image. The logs indicate a repetitive pattern of actions related to user validation, specifically for the "admin" user. This includes token validation, user detail retrieval, and user group fetching, which seems to execute in a loop without termination. This behaviour suggests there might be an issue with either the application logic or state management causing unnecessary repeated validations and queries.

**To Reproduce**
Steps to reproduce the behaviour are not directly observable through user interactions since the issue manifests at the application's backend/log output level. However, based on the logs, the sequence of actions leading to the loop can be inferred as follows:

1.     Pull and start the lldap/lldap:2024-02-06-debian-rootless container.
2.     Observe the container logs (enable DEBUG logging if not already enabled).
3.     Notice the repetitive logging of user validation, details retrieval, and group fetching for the "admin" user occurring in a short timeframe without any external triggers.
4.     The loop continues indefinitely, as seen in the provided log timestamps.

**Expected behavior**

The expected behaviour is for the application to validate the user's token, retrieve user details, and fetch user groups once per request or action without entering into a repetitive loop. After a successful validation and retrieval process, the application should proceed with normal operations without repeatedly performing the same actions for the same user unless triggered by a new request or action.

**Logs**

```
lldap_1  | 2024-02-08T15:54:09.511756116+00:00  DEBUG    │     ┕━ 🐛 [debug]:  | return: Ok(User { user_id: UserId(CaseInsensitiveString("admin")), email: Email(""), display_name: Some("Administrator"), creation_date: 2024-02-08T15:28:59.595063417, uuid: Uuid("9ab43c18-a2e8-3f9b-8d91-53b670e8816e"), attributes: [] })
...
(repeats with user group fetching and token validation)
...
lldap_1  | 2024-02-08T15:54:09.775744064+00:00  DEBUG    │     ┕━ 🐛 [debug]:  | return: Ok(User { user_id: UserId(CaseInsensitiveString("admin")), email: Email(""), display_name: Some("Administrator"), creation_date: 2024-02-08T15:28:59.595063417, uuid: Uuid("9ab43c18-a2e8-3f9b-8d91-53b670e8816e"), attributes: [] })
```

The provided logs show the repetitive loop involving user validation, details retrieval, and group fetching actions for the "admin" user, all occurring within a very short timeframe and without any user interaction suggesting a backend process issue with the lldap/lldap:2024-02-06-debian-rootless image.

**Comment by nitnelave** [comment]
Confirmed, and fixed. Thanks for the report!
