### ISSUE TITLE
[FEATURE REQUEST] Package lldap_set_password in lldap deb package or distribute a deb package in the same repository

### ISSUE THREAD

**Issue by ldidry** [lldap/lldap#854]
**Motivation**
I installed lldap from debian repository and wanted to use lldap-cli to set passwords but `lldap_set_password` is not available in the packages of the repository.

**Describe the solution you'd like**
Either add `lldap_set_password` to the `lldap` package or ship it as a separate package.

**Comment by nitnelave** [comment]
Hey! That's a perfectly understandable request. However, I'm not in control of the deb package, I don't even know who is :) Maybe there's a way to report issues closer to the package itself?

**Comment by ldidry** [comment]
According to the name of the repository, it should be @Masgalor.

@Masgalor Is it possible for you to either add `lldap_set_password` in `lldap` package or add a new package for it in your repository, please?

**Comment by Masgalor** [comment]
Hey @ldidry I am indeed responsible for the debian package.

I will find a way to ship the optional binaries `lldap_set_password` and `lldap_migration_tool` with the package.
Unfortunately I can not promise when I will find the time to work on it.
In the meantime, is it possible for you to use the precompiled `lldap_set_password` binary from the release section (here on Github)?
