### ISSUE TITLE
Traefik's PathPrefix supported?

### ISSUE THREAD

**Issue by habr05** [lldap/lldap#878]
Trying to configure lldap behind traefik so that I can get SSL connectivity. Everything works if I dedicate a sub.domain.tld to lldap. However, if I use PathPrefix (sub.domain.tld/lldp) I get a blank screen. Am I missing some setting or lldap does not support traefik's PathPrefix?

This is the configuration that I'm using for traefik.

    labels:
      - traefik.enable=true
      - traefik.http.routers.lldap.tls.certresolver=cloudflare
      - traefik.http.routers.lldap.entrypoints=websecure
      - traefik.http.routers.lldap.rule=Host(`${FQDN}`) && PathPrefix(`/lldap`)
      - traefik.http.routers.lldap.middlewares=lldap
      - traefik.http.routers.lldap.service=lldap

      - traefik.http.middlewares.lldap.stripprefix.prefixes=/lldap

      - traefik.http.services.lldap.loadbalancer.server.port=17170

**Comment by nitnelave** [comment]
See https://github.com/lldap/lldap/issues/870

But also, in terms of security, subdomains are highly recommended vs a subpath
