### ISSUE TITLE
[INTEGRATION] Trying to use LLDAP with LAM (Ldap Account Manager)

### ISSUE THREAD

**Issue by esp13** [lldap/lldap#886]
**Description of the service**
I know that I can access to the integrated web gui of lldap (on the default 17170 port) but I'm a beginner so I wanted to get a more visual gui display of my ldap directory.
I saw that LAM https://github.com/LDAPAccountManager/lam (Ldap Account Manager) has a "treeview" and wanted to give it a try with my lldap homeserver.
But again, I have difficulties to configure it correctly, I can see users but the groups nor the treeview are working.
Maybe adding a working configuration for LAM in https://github.com/lldap/lldap/tree/main/example_configs could be useful for other beginners :)

**What you've tried**

I have this in my configuration file (I display here only what seems relevant to my issue) (file generated from the configuration from the web gui of LAM):

```
ServerURL: ldap://lldapserveraddress:lldapserverport

serverDisplayName:

Admins: uid=admin,ou=people,dc=mysubdomain,dc=mydomain,dc=org

activeTypes: user,group

loginSearchSuffix: ou=people,dc=mysubdomain,dc=mydomain,dc=org

loginSearchFilter: uid=%USER%

loginSearchDN: uid=mylldapadmin,ou=people,dc=mysubdomain,dc=mydomain,dc=org

loginSearchPassword: thepasswordofmylldapadmin

httpAuthentication: false

modules: posixGroup_group_gidGenerator: range
modules: posixGroup_group_minGID: 10000
modules: posixGroup_group_maxGID: 20000
modules: posixGroup_group_hidememberUid: false
modules: posixAccount_user_uidGeneratorUsers: range
modules: posixAccount_user_minUID: 10000
modules: posixAccount_user_maxUID: 30000
modules: posixAccount_user_userNameSuggestion: @givenname@%sn%
modules: posixAccount_user_hidegecos: false
modules: posixAccount_user_hidepassword: false

types: suffix_user: ou=people,dc=mysubdomain,dc=mydomain,dc=org
types: attr_user: #uid;#givenName;#sn;#uidNumber;#gidNumber
types: modules_user: inetOrgPerson,posixAccount,shadowAccount
types: suffix_group: ou=groups,dc=mysubdomain,dc=mydomain,dc=org
types: attr_group: #cn;#gidNumber;#memberUID;#description
types: modules_group: posixGroup
types: customLabel_user:
types: filter_user:
types: customLabel_group: 
types: filter_group:
types: hidden_user:
types: hidden_group:
tools: treeViewSuffix: dc=mysubdomain,dc=mydomain,dc=org
```

**What's not working**

- In LAM web gui I can see users but some fields seems missing.
- In LAM web gui the groups nor the treeview aren't displayed.
- In lldap logs I get a lot of warnings, for example:
`WARN     │  │  ┝━ 🚧 [warn]: Ignoring unrecognized group attribute: departmentnumber\n\

                       To disable this warning, add it to "ignored_user_attributes" in the config.

WARN     │  │  ┝━ 🚧 [warn]: Ignoring unrecognized group attribute: ou\n\

                       To disable this warning, add it to "ignored_user_attributes" in the config.

WARN     │  │  ┝━ 🚧 [warn]: Ignoring unrecognized group attribute: o\n\

                       To disable this warning, add it to "ignored_user_attributes" in the config.

WARN     │  │  ┝━ 🚧 [warn]: Ignoring unrecognized group attribute: title\n\

                       To disable this warning, add it to "ignored_user_attributes" in the config.

WARN     │  │  ┝━ 🚧 [warn]: Ignoring unrecognized group attribute: employeetype\n\

                       To disable this warning, add it to "ignored_user_attributes" in the config.

WARN     │  │  ┝━ 🚧 [warn]: Ignoring unrecognized group attribute: businesscategory\n\

                       To disable this warning, add it to "ignored_user_attributes" in the config.

DEBUG    │  │  ┝━ expand_attribute_wildcards [ 4.87µs | 0.00% ] ldap_attributes: ["departmentNumber", "ou", "o", "title", "employeeType", "businessCategory"]`

**Comment by nitnelave** [comment]
LLDAP is known to not work very well with generic LDAP viewers: it doesn't implement a lot of the details that viewers rely on to dynamically discover the structure. This is not an area of focus for LLDAP, the recommended viewing interface is the provided web UI.
