### ISSUE TITLE
[FEATURE REQUEST] One checkbox per user to temporarily deny/allow access

### ISSUE THREAD

**Issue by r3flow** [lldap/lldap#904]
**Motivation**
When integrated with centralized remote access controller (jumphost, bastionhost), the authorised person responsible should be able to decide for which user and when to allow remote access.

**Describe the solution you'd like**
One checkbox per user to temporarily deny/allow access

**Comment by r3flow** [comment]
sorry, duplicated #750

**Comment by nitnelave** [comment]
(duplicate)
