### ISSUE TITLE
[INTEGRATION] uidNumber: missing on nslcd authentication

### ISSUE THREAD

**Issue by coldsobolev** [lldap/lldap#912]
**Describe the bug**
Unable to login via nslcd.

**To Reproduce**
1. Setup an LLDAP server inside Docker
2. Install nslcd, and configure to use the LLDAP server
3. Try to login to a user provided only by the LLDAP server

**Expected behavior**
Login works.
**Logs**
nslcd gives the following error: 
`uid=tuser,ou=people,dc=example,dc=com: uidNumber: missing`

If there are any other way to authenticate users into linux machines without local accounts, please provide alternatives.

**Comment by nitnelave** [comment]
uidNumber is not provided by default. If you use the latest LLDAP, you can create a custom user attribute uidNumber and set the value for each user.
The web UI doesn't fully support custom attributes yet (you can create them but not set values), but you can use lldap-cli as a friendlier interface than GraphQL.

**Comment by coldsobolev** [comment]
I am actually not sure what is causing the issue here, but I used the community CLI to add this and it didn't work. This is what I got:
```
lldap-cli $ ./lldap-cli schema attribute user add uidNumber integer
ERROR: Unknown type \AttributeType\
Unknown field \addUserAttribute\ on type \Mutation\
```
Any idea what is causing this? How does one do this directly via the API?

**Comment by nitnelave** [comment]
That's likely because you're using the stable version of LLDAP instead of the latest. User attributes have not technically been released yet (we're just waiting on the UI)

**Comment by coldsobolev** [comment]
Thank you. Could you give me an ETA?

**Comment by nitnelave** [comment]
Sorry for the (very) late answer. I don't have an ETA for a stable release (it's blocked on the web UI), but you can use the nightly releases.
