### ISSUE TITLE
[BUG] bootstrap.sh in rootless image

### ISSUE THREAD

**Issue by tbnguyen1407** [lldap/lldap#921]
**Describe the bug**

bootstrap.sh does not work in rootless image as apk must be run as root to install curl/jq/jo

**To Reproduce**

1. Run container with latest-alpine-rootless tag
2. Execute bootstrap.sh inside container
3. See error about executable not found

```
Command not found "curl"
Command not found "jq"
Command not found "jo"
```

**Expected behavior**

bootstrap.sh should work with rootless image.

**Logs**

N/A

**Additional context**

One solution is to bundle required packages in the image though this will increase the image size for people not using bootstrap.sh.

**Comment by nitnelave** [comment]
Yeah, I think we should install the packages by default.
