### ISSUE TITLE
[BUG] Broken web UI after user creation

### ISSUE THREAD

**Issue by mnowak-mirror** [lldap/lldap#925]
**Describe the bug**
The users web UI is broken after creating two users. It only shows:
```
Loading...
Error: TypeError: Failed to fetch
```

Also `lldap-cli` won't be able to list or modify the users anymore. It only returns this error:
```
ERROR: Connection error to lldap web interface: http://lldap.local.domain:<port>/api/graphql
```

However logging in with both created users still works as expected.

**To Reproduce**
1. Setup LLDAP with PostgreSQL backend
2. Create a user:
    * Username: user.name
    * Email: user.name@local.domain
    * Display Name: User Name
    * First Name: User
    * Last Name: Name
    * Password: .....
3. Create a second user:
    * Username: adm.user.name
    * Email: adm.user.name@local.domain
    * Display Name: ADM User Name
    * First Name: ADM User
    * Last Name: Name
    * Password: ......
4. The error will immediately show after saving the second user

**Expected behavior**
The second user doesn't break the UI.

**Logs**
```
Jul 02 22:31:06 lldap.local.domain lldap[75050]: thread 'actix-rt|system:0|arbiter:0' panicked at server/src/domain/sql_user_backend_handler.rs:142:13:
Jul 02 22:31:06 lldap.local.domain lldap[75050]: Attributes are not sorted, users are not sorted, or previous user didn't consume all the attributes
```

**Additional context**
Access to the web UI is via HTTPS through a HAProxy instance. Other than that pretty straight forward installation with Postgres as backend.

**Comment by nitnelave** [comment]
Can you try https://github.com/lldap/lldap/issues/821#issuecomment-1923995870 ?

It's a known issue, we need to change the collate of the column for PostgreSQL to C.

**Comment by mnowak-mirror** [comment]
Forgot to mention I didn't use docker to set it up. I use Ansible to install LLDAP from the CentOS-9 Stream repo since I'm a fan of one VM per application I host. Same goes for the PostgreSQL server.

I'm no expert when it comes to databases, but I'll play around with it in the next few days when I find the time. Doesn't hurt to learn a few new things.

**Comment by mnowak-mirror** [comment]
Creating the DB with lc_collate=C indeed works as expected. Thanks for the quick help
