### ISSUE TITLE
[BUG] Authelia example has deprecated keys

### ISSUE THREAD

**Issue by seanlongnyc** [lldap/lldap#929]
**Describe the bug**
Configuration keys deprecated in 4.38.0 of Authelia generate noise in logging. Currenly these settings are auto-mapped to new value but expected to break in 5.0.0

Keys to change:
| old name | new name |
| --- | --- |
| authentication_backend.ldap.group_name_attribute | authentication_backend.ldap.attributes.group_name |
| authentication_backend.ldap.username_attribute | authentication_backend.ldap.attributes.username |
| authentication_backend.ldap.url | authentication_backend.ldap.address |
| authentication_backend.ldap.display_name_attribute | authentication_backend.ldap.attributes.display_name |
 

**To Reproduce**
1. Use the provided Authelia example when starting Authelia
2. Check logging

**Expected behavior**

**Logs**
`msg="Configuration: configuration key '[OLD_KEY_NAME]' is deprecated in 4.38.0 and has been replaced by '[NEW_KEY]': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"`

**Comment by nitnelave** [comment]
Thanks! Could you make a PR to update the example?
