### ISSUE TITLE
Bootrap.sh seems not executable

### ISSUE THREAD

**Issue by flashpixx** [lldap/lldap#936]
**Describe the bug**
I'm try to run the `boostrap.sh` as init container on K8 and follow the the documentation https://github.com/lldap/lldap/blob/main/example_configs/bootstrap/bootstrap.md

**To Reproduce**

Try to run `docker run lldap/lldap:2024-07-20-alpine /bootstrap/bootstrap.sh` or I'm using `/app/bootstrap.sh`
The output is:

```
entrypoint] Copying the default config to /data/lldap_config.toml
[entrypoint] Edit this file to configure LLDAP.
> Setup permissions..
> Starting lldap..

error: unrecognized subcommand '/bootstrap/bootstrap.sh'

Usage: lldap <COMMAND>

For more information, try '--help'.
```

so it seems that the script could not be executed

**Expected behavior**
Executing the boostrap script to add user and groups

**Comment by nitnelave** [comment]
The way you're invoking docker run just passes the bootstrap path to the LLDAP startup script (which expects an lldap command like "run").

What you want is to call the bootstrap instead of the LLDAP startup script, by changing the entry point of the container:
`docker run lldap/lldap:2024-07-20-alpine --entrypoint /bootstrap/bootstrap.sh`

**Comment by flashpixx** [comment]
The correct command seems to be:

```
 docker run --entrypoint /app/bootstrap.sh lldap/lldap:2024-07-20-alpine
```

But I'm not sure that it is posible to overwrite the entrypoint in a pod setup within Kubernetes, inmho I overwrite the command, see the docs https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
It would be nice to run the boostrap script on an init container, and if the pod security is activated so it seems to to be possible to install other tools within the container

But in general great work, I will use it for a data science project as central auth structure e.g. for Airflow, Jupyter, Spark etc

**Comment by nitnelave** [comment]
I'm not very familiar with Kubernetes, so I didn't follow all your answer. 

Is there anything I can help with?

**Comment by flashpixx** [comment]
I think it is useful to change the `docker-entrypoint.sh` script, but you have got a basic [Kubernetes config](https://github.com/lldap/lldap?tab=readme-ov-file#with-kubernetes), but a [Helm Chart](https://helm.sh/) would be nice.
I'm using LLDAP at the moment and I can make a fork for your project. Can I send a pull request for a full Helm Chart to this repo, but it will take some time

**Comment by nitnelave** [comment]
There's already a helm chart with bootstrap support (unofficial): https://artifacthub.io/packages/helm/djjudas21/lldap

**Comment by flashpixx** [comment]
Thanks this is nice
