### ISSUE TITLE
[BUG] Queries of the form "|(member=myuser)(member=uid=myuser,ou=...)" fail.  (blocks linux groups via libnss-ldapd)

### ISSUE THREAD

**Issue by sagi-glacia** [lldap/lldap#949]
The following ldapsearch query returns no results.
```
(&(&(objectClass=groupOfUniqueNames)(is-unix-group=1))(|(member=myuser)(member=uid=myuser,ou=people,dc=example,dc=net)))
```

Here is an [lldap debug log](https://github.com/user-attachments/files/16638068/log.txt) for this query.

The following ldapsearch query returns many results.
```
(&(&(objectClass=groupOfUniqueNames)(is-unix-group=1))(|(member=uid=myuser,ou=people,dc=example,dc=net)))
```

**Expected behavior**

While lldap does not supply `member=myuser`, only `member=uid=myuser,ou=people,dc=example,dc=net`, the OR query should result in the same results being returned for both queries, since one of its subqueries does match in all cases.

**Additional context**

When lldap is used with libnss-ldapd to provide user/group service to linux hosts, group membership is broken for users.  This results in users not being assigned their correct groups on login, resulting in no access to resources.

**Comment by nitnelave** [comment]
The query didn't work because the filter `(member=groupName)` was considered malformed and aborted the entire query.

I added support for such a filter, and made it so that errors in filters don't abort the query (they're just replaced with `false`)
