### ISSUE TITLE
[BUG] Presence filters are not properly handled by lldap

### ISSUE THREAD

**Issue by sagi-glacia** [lldap/lldap#950]
Presence filters (`(unix-uid=*)`) are not respected by lldap.  Instead they are currently executed as a schema check rather than a data check.

[Reference](https://ldap.com/ldap-filters/) [documentation](https://ldapwiki.com/wiki/Wiki.jsp?page=Presence%20SearchFilter) for Presence Filters.

**To Reproduce**

1. Create a custom attribute.
2. Populate it with a value on some users and not all users.
3. Perform ldapsearch `(your-attribute=*)`
4. Observe that all users are returned, not just the ones with the attribute set.

**Expected behavior**

lldap should return only the users with the attribute present when queried with a presence filter.

**Additional context**

This silent failure misbehavior has security consequences.  For instance, the documentation for `libnss-ldapd` contains this passage:

```text
For  example,  to  check  that  the  user has a proper authorizedService value if the attribute is present (this almost emulates the pam_check_service_attr option in PADL's
pam_ldap):

(&(objectClass=posixAccount)(uid=$username)(|(authorizedService=$service)(!(authorizedService=*))))
```

If users were to trust this (or indeed chose to use `libpam-ldap` instead which likely does something similar _without_ showing the user the exact details of the query when `authorizedService` or `host` checks are performed), lldap would be exposing them to explicitly unauthorized logins on Hosts B-Z from users that should be authorized only on Host A.

**Comment by nitnelave** [comment]
Fixed in the latest version.
