### ISSUE TITLE
[INTEGRATION] Trying to use LDAP authentication on a Raspberry Pi

### ISSUE THREAD

**Issue by v-mod** [lldap/lldap#984]
**Checklist**
- [ ] Check if there is already an [example config](https://github.com/lldap/lldap/tree/main/example_configs) for it.
- [ ] Try to figure out the configuration values for the new service yourself.
  - You can use other example configs for inspiration.
  - If you're having trouble, you can ask on [Discord](https://discord.gg/h5PEdRMNyP) or create an issue.
  - If you succeed, make sure to contribute an example configuration, or a configuration guide.
- If you hit a block because of an unimplemented feature, create an issue.

**Description of the service**
I'm using nslcd on a Raspberry pi 3 to try and configure LDAP.  Using an entry in the hosts file to point to the docker IP Address.

**What you've tried**
```
# The user and group nslcd should run as.
uid nslcd
gid nslcd

# The location at which the LDAP server(s) should be reachable.
uri ldap://ldap.******.uk:3890/.

# The search base that will be used for all queries.
base dc=*******,dc=uk

# The LDAP protocol version to use.
#ldap_version 3

# The DN to bind with for normal lookups.
binddn uid=rpi,ou=people,dc=*******,dc=uk
bindpw *********
```

**What's not working**
Error logs, error screenshots, features that are not working, missing features.
```
● nslcd.service - LSB: LDAP connection daemon
     Loaded: loaded (/etc/init.d/nslcd; generated)
     Active: active (running) since Sun 2024-09-29 16:57:51 BST; 5min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 297516 ExecStart=/etc/init.d/nslcd start (code=exited, status=0/SUCCESS)
      Tasks: 6 (limit: 762)
        CPU: 134ms
     CGroup: /system.slice/nslcd.service
             └─297525 /usr/sbin/nslcd

Sep 29 16:57:51 ultimate-rpi3 systemd[1]: Starting nslcd.service - LSB: LDAP connection daemon...
Sep 29 16:57:51 ultimate-rpi3 nslcd[297525]: version 0.9.12 starting
Sep 29 16:57:51 ultimate-rpi3 nslcd[297525]: accepting connections
Sep 29 16:57:51 ultimate-rpi3 nslcd[297516]: Starting LDAP connection daemon: nslcd.
Sep 29 16:57:51 ultimate-rpi3 systemd[1]: Started nslcd.service - LSB: LDAP connection daemon.
Sep 29 16:58:16 ultimate-rpi3 nslcd[297525]: [b127f8] <passwd=******_testing"> uid=******_testing,ou=people,dc=*******,dc=uk: uidNumber: missing
```

**Comment by nitnelave** [comment]
Hi! 
Have you checked the  pam authentication guide? I think it should cover most of the bases.

https://github.com/lldap/lldap/blob/main/example_configs%2Fpam%2FREADME.md

**Comment by v-mod** [comment]
oh my god thank you so much for this I didn't see this. i think this should be able to fix it as it seems to contain the custom properties it was lacking.
